config:
  aws:profile: dev

  # Helm charts enabled
  charts:ingress_nginx_external_enabled: True
  charts:argocd_enabled: False

  charts:argocd_version: "5.50.1"
  charts:argocd_namespace: "argocd"

  argocd:ingress_hostname: "argocd.dev.lokalise.cloud"
  argocd:ingress_protocol: "http"
  argocd:ingress_class_name: "nginx-external"
  argocd:redis_ha_enabled: True
  argocd:redis_ha_storage_size: "10Gi"
