name: helm-system-main
runtime:
  name: python
  options:
    virtualenv: venv
description: Helm charts

config:
  org: luismiguelsaez

  aws:region: eu-central-1

  helm:name_prefix: main

  # Helm charts enabled
  charts:metrics_server_enabled: True
  charts:cluster_autoscaler_enabled: True
  charts:karpenter_enabled: True
  charts:aws_load_balancer_controller_enabled: True
  charts:external_dns_enabled: True
  charts:ebs_csi_driver_enabled: True
  charts:ingress_nginx_external_enabled: False
  charts:ingress_nginx_internal_enabled: False
  charts:opensearch_enabled: False
  charts:argocd_enabled: False
  charts:argocd_apps_enabled: False

  # Helm charts versions
  charts:metrics_server_version: "3.11.0"
  charts:karpenter_version: "v0.32.1"
  charts:cluster_autoscaler_version: "9.32.0"
  charts:aws_load_balancer_controller_version: "1.6.2"
  charts:ebs_csi_driver_version: "2.25.0"
  charts:external_dns_version: "1.13.1"
  charts:opensearch_version: "2.14.1"
  charts:ingress_nginx_external_version: "4.8.3"
  charts:ingress_nginx_internal_version: "4.8.3"
  charts:argocd_version: "5.51.4"
  charts:argocd_apps_version: "1.4.1"

  # Helm charts namespaces
  charts:metrics_server_namespace: "kube-system"
  charts:karpenter_namespace: "cloud-controllers"
  charts:cluster_autoscaler_namespace: "cloud-controllers"
  charts:aws_load_balancer_controller_namespace: "cloud-controllers"
  charts:ebs_csi_driver_namespace: "cloud-controllers"
  charts:external_dns_namespace: "cloud-controllers"
  charts:opensearch_namespace: "opensearch"
  charts:ingress_nginx_external_namespace: "ingress"
  charts:ingress_nginx_internal_namespace: "ingress"
  charts:argocd_namespace: "argocd"
  charts:argocd_apps_namespace: "argocd"

  # Ingress settings
  ingress:external_ssl_enabled: True
  ingress:internal_ssl_enabled: False
  ingress:external_ssl_cert_arns: ""
  ingress:internal_ssl_cert_arns: ""
  ingress:external_domain: ""
  ingress:internal_domain: ""

  # Opensearch settings
  opensearch:storage_size: 20Gi
  opensearch:replicas: 3
  opensearch:memory_mb: "2000"
  opensearch:cpu: 1000m

  # ArgoCD settings
  argocd:ingress_hostname: ""
  argocd:controller_replicas: 3
  argocd:applicationset_replicas: 3
  argocd:controller_resources: '{"limits": {"cpu": "1000m", "memory": "2000Mi"}, "requests": {"cpu": "1000m", "memory": "2000Mi"}}'
  argocd:repo_server_resources: '{"limits": {"cpu": "1000m", "memory": "512Mi"}, "requests": {"cpu": "1000m", "memory": "512Mi"}}'
  argocd:ingress_protocol: "https"
  argocd:ingress_class_name: "nginx-internal"
  argocd:redis_ha_enabled: False
  argocd:redis_ha_storage_size: "20Gi"

  ebs_csi_driver:storage_class_name: "ebs"
