name: helm-system-main
runtime:
  name: python
  options:
    virtualenv: venv
description: Helm charts

config:
  org: luismiguelsaez

  aws:region: eu-central-1

  helm:name_prefix: main

  # Helm charts enabled
  charts:cluster_autoscaler_enabled: True
  charts:karpenter_enabled: True
  charts:aws_load_balancer_controller_enabled: True
  charts:external_dns_enabled: True
  charts:ebs_csi_driver_enabled: False

  # Helm charts versions
  charts:karpenter_version: "0.16.3"
  charts:cluster_autoscaler_version: "9.29.3"
  charts:aws_load_balancer_controller_version: "1.6.1"
  charts:ebs_csi_driver_version: "2.23.1"
  charts:external_dns_version: "1.13.1"

  # Helm charts namespaces
  charts:karpenter_namespace: "cloud-controllers"
  charts:cluster_autoscaler_namespace: "cloud-controllers"
  charts:aws_load_balancer_controller_namespace: "cloud-controllers"
  charts:ebs_csi_driver_namespace: "cloud-controllers"
  charts:external_dns_namespace: "cloud-controllers"
