config:
  aws:profile: dev

  # Helm charts enabled
  charts:metrics_server_enabled: True
  charts:cluster_autoscaler_enabled: True
  charts:karpenter_enabled: True
  charts:aws_load_balancer_controller_enabled: True
  charts:external_dns_enabled: True
  charts:ebs_csi_driver_enabled: False
  charts:ingress_nginx_external_enabled: True
  charts:ingress_nginx_internal_enabled: False
  charts:opensearch_enabled: False
  charts:argocd_enabled: True

  charts:argocd_version: "5.50.1"
  charts:argocd_namespace: "argocd"
