name: helm-system-main
runtime:
  name: python
  options:
    virtualenv: venv
description: Helm charts

config:
  org: luismiguelsaez

  aws:region: eu-central-1

  helm:name_prefix: main

  charts:karpenter_version: "0.16.3"
  charts:cluster_autoscaler_version: "9.29.3"
